### ISSUE TITLE
Versioning strategy for custom actions and workflows

### ISSUE THREAD

**Issue by devtobi** [it-at-m/lhm_actions#48]
**Problem**
I created a reusable workflow for CodeQL in this repository (see https://github.com/it-at-m/.github/pull/26) thats used in https://github.com/it-at-m/refarch-templates/pull/352.
This is achieved by the line:

```yaml
uses: it-at-m/.github/.github/workflows/codeql.yml@main
```

However the reference to main has potential side effects when the workflow gets updated on the main branch of this repository.
Thats why we should introduce a versioning strategy for all custom actions and workflows. (either via Branch names or Git Tags).

On top of that it would be interesting if Renovatebot is able to bump to new version numbers when the actions/workflows get new releases. If not I'd encourage a simple versioning scheme like `v1`, `v2` etc. If Renovatebot is capable, we could use a more fine granular version like `1.0.0` as well.

- [x] it-at-m/lhm_actions#37
- [x] it-at-m/lhm_actions#36
- [x] it-at-m/.github#112
- [x] it-at-m/.github#113

**Comment by hupling** [comment]
erledigt
